"""
Main Pipeline — Audience Comment Miner
Combines: Token Optimization + Debugging + Production Ready
"""

import os
import json
import logging
import google.generativeai as genai
from dotenv import load_dotenv
from optimizer import build_optimized_prompt, call_with_cache
from debugger import FixedPipeline, validate_json_output, logger

load_dotenv()
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
model = genai.GenerativeModel("gemini-2.0-flash")

REQUIRED_KEYS = [
    "questions",
    "content_requests",
    "complaints",
    "praise",
    "top_content_ideas"
]


def fetch_youtube_comments(video_id: str, api_key: str) -> list[str]:
    """
    Fetch real YouTube comments using YouTube Data API v3
    Falls back to sample data if API not available
    """
    import requests

    url = "https://www.googleapis.com/youtube/v3/commentThreads"
    params = {
        "part": "snippet",
        "videoId": video_id,
        "maxResults": 100,
        "order": "relevance",
        "key": api_key
    }

    try:
        response = requests.get(url, params=params, timeout=10)
        response.raise_for_status()
        data = response.json()

        comments = []
        for item in data.get("items", []):
            text = (
                item["snippet"]["topLevelComment"]
                ["snippet"]["textDisplay"]
            )
            comments.append(text)

        logger.info(f"✅ Fetched {len(comments)} real comments")
        return comments

    except Exception as e:
        logger.warning(f"YouTube API failed: {e}")
        logger.info("Using sample comments for demo...")

        # Fallback sample comments
        return [
            "Can you make a Python tutorial?",
            "Love your content! Keep it up!",
            "The audio quality was really bad",
            "Please do a video on machine learning!",
            "How do you edit your videos?",
            "This helped me so much, thank you!",
            "Can you explain neural networks?",
            "More coding challenges please!",
            "How do I get started with AI?",
            "Can you cover React hooks next?",
            "Amazing tutorial! Subscribed!",
            "The background music is too loud",
            "More DSA videos please!",
            "What laptop do you use for coding?",
            "Can you do a full stack project?",
        ]


def analyze_comments_with_gemini(comments: list[str]) -> dict:
    """
    Analyze comments using optimized Gemini prompt
    Uses caching to avoid repeat API calls
    """
    # Build optimized prompt (Part 1 optimization)
    prompt = build_optimized_prompt(comments)

    # Call with cache (Part 1 optimization 2)
    result = call_with_cache(prompt)
    raw_output = result["result"]

    # Validate output (Part 2 debugging)
    is_valid, data = validate_json_output(
        raw_output,
        REQUIRED_KEYS
    )

    if not is_valid:
        raise ValueError("AI output validation failed!")

    return data


def generate_report(analysis: dict, channel_name: str = "Your Channel") -> str:
    """Generate clean weekly report"""
    ideas = analysis.get("top_content_ideas", [])
    questions = analysis.get("questions", [])
    requests = analysis.get("content_requests", [])
    complaints = analysis.get("complaints", [])
    praise = analysis.get("praise", [])

    report = f"""
📊 WEEKLY AUDIENCE INSIGHTS — {channel_name}
{'=' * 50}

🔝 TOP CONTENT IDEAS (ranked by demand):
"""
    for idea in ideas[:5]:
        report += (
            f"  #{idea.get('rank', '?')}: "
            f"{idea.get('idea', 'N/A')}\n"
            f"      → {idea.get('reason', '')}\n"
        )

    report += f"\n❓ QUESTIONS YOUR AUDIENCE IS ASKING ({len(questions)}):\n"
    for q in questions[:5]:
        report += f"  • {q}\n"

    report += f"\n📋 CONTENT REQUESTS ({len(requests)}):\n"
    for r in requests[:5]:
        count = r.get('count', 1)
        idea = r.get('idea', 'N/A')
        report += f"  • {idea} (requested {count}x)\n"
        # Show source comments
        source = r.get('comments', [])
        for s in source[:2]:
            report += f"      └ \"{s}\"\n"

    report += f"\n😤 COMPLAINTS TO ADDRESS ({len(complaints)}):\n"
    for c in complaints[:3]:
        report += f"  • {c}\n"

    report += f"\n❤️  WHAT THEY LOVE ({len(praise)}):\n"
    for p in praise[:3]:
        report += f"  • {p}\n"

    report += f"\n{'=' * 50}\n"
    report += "Generated by Audience Comment Miner Agent\n"

    return report


def run_full_pipeline(
    video_id: str = None,
    channel_name: str = "Demo Channel"
) -> str:
    """
    Full production pipeline:
    1. Fetch YouTube comments
    2. Optimize + analyze with Gemini
    3. Generate report
    """
    logger.info("🚀 Starting Audience Comment Miner Pipeline")

    youtube_api_key = os.getenv("YOUTUBE_API_KEY", "")
    video_id = video_id or os.getenv(
        "YOUTUBE_VIDEO_ID", "dQw4w9WgXcQ"
    )

    # Step 1: Fetch comments
    comments = fetch_youtube_comments(video_id, youtube_api_key)

    # Step 2: Analyze
    analysis = analyze_comments_with_gemini(comments)

    # Step 3: Generate report
    report = generate_report(analysis, channel_name)

    logger.info("✅ Pipeline completed successfully!")
    return report


if __name__ == "__main__":
    report = run_full_pipeline(channel_name="My YouTube Channel")
    print(report)
